from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", extra="ignore")

    JWT_SECRET: str
    SESSION_COOKIE_NAME: str = "focus_session"

    # --- Auth ---
    AUTH_PASSWORD_HASH: str            # bcrypt hash, generated by bin/hash-password.py
    AUTH_TOTP_SECRET: str = ""         # leave blank to disable 2FA

    APP_BASE_URL: str = "https://focus.baltito.com"

    DATABASE_URL: str = "sqlite:////data/focus.db"

    # --- LLM + Voice (OpenAI-compatible: Groq default) ---
    LLM_BASE_URL: str = "https://api.groq.com/openai/v1"
    LLM_API_KEY: str
    LLM_MODEL: str = "llama-3.3-70b-versatile"
    WHISPER_MODEL: str = "whisper-large-v3-turbo"
    LLM_TIMEOUT: int = 60


settings = Settings()
